[package]
name = "uemu_rvxxix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["rv32i", "littleEndian"]
rv32i = []
rv64i = []
bigEndian = []
littleEndian = []


[dependencies]
